name: Python CI/CD Pipeline

on: push

jobs:
  lint-the-code:
    name: All checks then build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Black linter
        uses: psf/black@stable
        with:
          options: "--check --verbose"

  test-to-build:
    name: All checks then build
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Get Dependencies
        run: pip install -r requirements.txt

      - name: get Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libegl1 libopengl0 libxkbcommon-x11-0 libdbus-1-3

      - name: Run tests
        #run: xvfb-run pytest
        run: QT_DEBUG_PLUGINS=1 xvfb-run pytest
