name: Python CI/CD Pipeline

on: push

jobs:
  lint-the-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with: 
          python-version: '3.13'

      - name: Get Dependecies
        run: pip install -r requirements.txt

      - name: Run Black linter
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"


